### PR TITLE
models and working template

### PR DESCRIPTION
**Pull request by royhirakp**
hey! this push for the models and the node js template. need more update. route path, collection name is not push . please check

### CODE REVIEW

**Review by ashwinramuk — APPROVED** [review]
Replaced mongoDB model fieldNames with camelCase and included dotenv/config in index.js

**Review by jilanibashaP — APPROVED** [review]
ok

**Review by jilanibashaP — APPROVED** [review]
ok

**Review by jilanibashaP — APPROVED** [review]
ok

**Review by jilanibashaP — APPROVED** [review]
ok

**Pull request merged**
